/**
typedef enum SqlType{
    SQLTYPE_UNKNOWN = 0,
    SQLTYPE_SELECT,
    SQLTYPE_UPDATE,
    SQLTYPE_INSERT,
    SQLTYPE_REPLACE,
    SQLTYPE_DELETE,
    SQLTYPE_TRANSACTION_BEGIN,
    SQLTYPE_TRANSACTION_START,
    SQLTYPE_TRANSACTION_COMMIT,
    SQLTYPE_TRANSACTION_ROLLBACK,
    SQLTYPE_CREATE_TABLE,
    SQLTYPE_DROP_TABLE,
    SQLTYPE_SET,
    SQLTYPE_SET_NAMES,
    SQLTYPE_SET_CHARACTER_SET,
    SQLTYPE_SHOW,
}SqlType;
*/

var types = ["UNKNOWN", "SELECT", "UPDATE", "INSERT", "REPLACE", "DELETE", "TRANSACTION_BEGIN", "TRANSACTION_START", "TRANSACTION_COMMIT", "TRANSACTION_ROLLBACK", "CREATE_TABLE", "DROP_TABLE", "SET", "SET_NAMES", "SET_CHARACTER_SET", "SHOW"];
module.exports = types;
